import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import EditTool from '../lib/EditTool'

import { MobileMockup, WindowMockup, BrowserMockup } from 'react-mockup'
import 'react-mockup/dist/index.css'
import GeneratedComponent from '../lib/GeneratedComponent';


export default function Home() {
  const [currentMockupType, setCurrentMockupType] = useState('BrowserMockup');

  const [mockupType, setMockupType] = useState('');
  const [mockupAngleX, setMockupAngleX] = useState(0);
  const [mockupAngleY, setMockupAngleY] = useState(0);
  const [mockupShadow, setMockupShadow] = useState('');
  const [mockupBorder, setMockupBorder] = useState('');
  const [mockupColor, setMockupColor] = useState('white');
  const [mockupAccentColor, setMockupAccentColor] = useState('black');
  const [mockupUrlValue, setMockupUrlValue] = useState('react-mockup-editor');

  return (
    <div className={'container'}>
      <Head>
        <title>Mockup Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'main'}>
        <h1>React Mockup Editor</h1>
        <section className={'links'}>
          <Link href="/">About</Link>
          <Link href="/">Github</Link>
          <Link href="/">NPM</Link>
        </section>
        <section>
          <div>
            <h2>Edit Mockup</h2>
            <div>
              <div>
                <span>Switch to: </span>
                <code onClick={() => setCurrentMockupType('BrowserMockup')}>BrowserMockup</code>
                <code onClick={() => setCurrentMockupType('MobileMockup')}>MobileMockup</code>
                <code onClick={() => setCurrentMockupType('WindowMockup')}>WindowMockup</code>
              </div>
              <h3>CurrentMockup Type: <code>{currentMockupType}</code></h3>
            </div>
            <div className={'editor'}>
              <div className={'mockupContainer'}>
                {currentMockupType === 'BrowserMockup' &&
                  <BrowserMockup
                    src={""}
                    type={mockupType}
                    angleX={mockupAngleX + 'deg'}
                    angleY={mockupAngleY + 'deg'}
                    shadow={mockupShadow}
                    border={mockupBorder}
                    color={mockupColor}
                    accentColor={mockupAccentColor}
                    urlValue={mockupUrlValue}
                  />
                }
                {currentMockupType === 'MobileMockup' &&
                  <>
                    <h4>This Component is still in its beta development</h4>
                    <MobileMockup
                      src={""}
                      type={mockupType}
                      angleX={mockupAngleX + 'deg'}
                      angleY={mockupAngleY + 'deg'}
                      // shadow={mockupShadow}
                      // border={mockupBorder}
                      color={mockupColor}
                    />
                  </>
                }
                {currentMockupType === 'WindowMockup' &&
                  <WindowMockup
                    src={""}
                    type={mockupType}
                    angleX={mockupAngleX + 'deg'}
                    angleY={mockupAngleY + 'deg'}
                    shadow={mockupShadow}
                    border={mockupBorder}
                    color={mockupColor}
                  />
                }
              </div>
              <div className={'editorPannel'}>
                {currentMockupType !== 'MobileMockup' &&
                  <>
                    <EditTool name="Type" type={mockupType}>
                      <button onClick={() => setMockupType('')}>Default</button>
                      <button onClick={() => setMockupType('mac')}>Mac</button>
                      <button onClick={() => setMockupType('outline')}>Outline</button>
                      <button onClick={() => setMockupType('chrome')}>Chrome</button>
                    </EditTool>
                    <EditTool name="Border" type={mockupBorder}>
                      <button onClick={() => setMockupBorder('')}>Default</button>
                      <button onClick={() => setMockupBorder('none')}>None</button>
                    </EditTool>
                    <EditTool name="Shadow" type={mockupShadow}>
                      <button onClick={() => setMockupShadow('')}>Default</button>
                      <button onClick={() => setMockupShadow('none')}>None</button>
                      <input placeholder="Custom" type="text" />
                    </EditTool>
                  </>
                }
                {currentMockupType === 'BrowserMockup' &&
                  <EditTool
                    name="URL Value"
                    type={''}
                  >
                    <input onChange={(e) => { e.preventDefault(); setMockupUrlValue(e.target.value) }} />
                  </EditTool>
                }
                <EditTool
                  name="Mockup Angle"
                  type={''}
                  seperateSlot={
                    <>
                      <h4 style={{ margin: '0 0 1em 0' }}>AngleX: <code>{mockupAngleX} degrees</code></h4>
                      <h4 style={{ margin: '0 0 1em 0' }}>AngleY: <code>{mockupAngleY} degrees</code></h4>
                    </>
                  }>
                  <button onClick={() => setMockupAngleX(mockupAngleX - 0.5)}>Top</button>
                  <button onClick={() => setMockupAngleX(mockupAngleX + 0.5)}>Bottom</button>
                  <button onClick={() => setMockupAngleY(mockupAngleY + 0.5)}>Left</button>
                  <button onClick={() => setMockupAngleY(mockupAngleY - 0.5)}>Right</button>
                </EditTool>
                <EditTool name="Color" type={mockupColor}>
                  <button onClick={() => setMockupColor('white')}>White</button>
                  <button onClick={() => setMockupColor('black')}>Black</button>
                  <button onClick={() => setMockupColor('grey')}>Grey</button>
                  <input type="color" value={mockupColor} onChange={(e) => { e.preventDefault(); setMockupColor(e.target.value); }} />
                </EditTool>
                {currentMockupType === 'BrowserMockup' &&
                  <EditTool name="Accent Color" type={mockupAccentColor}>
                    <button onClick={() => setMockupAccentColor('white')}>White</button>
                    <button onClick={() => setMockupAccentColor('black')}>Black</button>
                    <button onClick={() => setMockupAccentColor('grey')}>Grey</button>
                    <input type="color" value={mockupAccentColor} onChange={(e) => { e.preventDefault(); setMockupAccentColor(e.target.value); }} />
                  </EditTool>
                }
              </div>
            </div>
          </div>
          <div>
            <h2>Generated React Component</h2>
            <GeneratedComponent
              componentName={currentMockupType}
              url={'url'}
              mockupType={mockupType}
              mockupAngleX={mockupAngleX}
              mockupAngleY={mockupAngleY}
              mockupShadow={mockupShadow}
              mockupBorder={mockupBorder}
              mockupColor={mockupColor}
              mockupAccentColor={mockupAccentColor}
            />
          </div>
        </section>
      </main>

      <footer className={'footer'}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed & Developed by 501A
        </a>
      </footer>
    </div>
  )
}
