import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import EditTool from '../lib/EditTool'

import { MobileMockup, WindowMockup, BrowserMockup } from 'react-mockup'
import 'react-mockup/dist/index.css'
import GeneratedComponent from '../lib/GeneratedComponent';


export default function Home() {

  return (
    <div className={'container'}>
      <Head>
        <title>Mockup Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'main'}>
        <h1>React Mockup</h1>
        <section className={'links'}>
          <Link href="/editor">Editor</Link>
          <Link href="https://github.com/501A-Designs">Developer GitHub</Link>
          <Link href="https://github.com/501A-Designs/react-mockup">Github</Link>
          <Link href="https://www.npmjs.com/package/react-mockup">NPM</Link>
        </section>
        <section style={{display: 'grid', gridTemplateColumns:'1fr 1fr', marginTop:'2em', marginBottom:'2em', gap:'1em'}}>
          <BrowserMockup
            src={'https://www.psdstack.com/wp-content/uploads/2019/08/copyright-free-images-750x420.jpg'}
            type={'mac'}
            urlValue={'My Cool Website'}
            color={'white'}
            border={'none'}
            accentColor={'black'}
            windowControlPosition={'left'}
          />
          <div style={{padding: '1em'}}>
            <pre>
              {`
<BrowserMockup            
  src={'./mycoolimage.jpg'}
  type={'mac'}
  urlValue={'My Cool Website'}
  color={'white'}
  border={'none'}
  accentColor={'black'}
  windowControlPosition={'left'}
/>
              `}
            </pre>
            <div>
              <strong>Get started now:</strong>
              <p>
                Install: <code>npm i --save react-mockup</code>
              </p>
            </div>
          </div>
        </section>
      </main>

      <footer className={'footer'}>
        <a
          href="https://501a.netlify.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed & Developed by 501A
        </a>
      </footer>
    </div>
  )
}
